### ISSUE TITLE
[Feature] AI 서버 fetch API 구현

### ISSUE THREAD

**Issue by speardragon** [sharebookshelf/Gongcheck-BE#1]
### Description
사용자가 /upload 엔드포인트에 대해 user-id값을 헤더에 담고 multipart/form-data의 file 형식으로 여러 이미지와 함께 요청을 보내면 해당 이미지를 AI server로 fetch하여 가져온 데이터를 기반으로 다음 데이터베이스 작업을 진행한다.
1. Bookshelf 테이블에 AI server 측에 저장된 책장 이미지 저장 경로 및 사용자 Id 저장
2. 인식된 책들을 Book 테이블에 저장(중복된 책은 넣지 않음)
3. userId 별 book을 UserBook테이블에 저장

### TODO
- [x] AI 서버 URL fetch 
- [x] 데이터베이스 트랜잭션 구현
- [x] API 기능 확인
